/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.plantitasdelnorte;

/**
 *
 * @author cesarg.rivas
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        escritorio = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        compraRegistrar = new javax.swing.JMenuItem();
        crearClientes = new javax.swing.JMenu();
        crearCliente = new javax.swing.JMenuItem();
        modificarClientes = new javax.swing.JMenuItem();
        borrarClientes = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        crearProducto = new javax.swing.JMenuItem();
        productoVer = new javax.swing.JMenuItem();
        jMenu6 = new javax.swing.JMenu();
        reporteCompra = new javax.swing.JMenuItem();
        reporteVenta = new javax.swing.JMenuItem();
        reporteInventario = new javax.swing.JMenuItem();
        jMenu7 = new javax.swing.JMenu();
        usuarioCrear = new javax.swing.JMenuItem();
        usuarioModificar = new javax.swing.JMenuItem();
        usuarioBorrar = new javax.swing.JMenuItem();
        jMenu8 = new javax.swing.JMenu();
        opcInfo = new javax.swing.JMenuItem();

        jMenu3.setText("File");
        jMenuBar2.add(jMenu3);

        jMenu4.setText("Edit");
        jMenuBar2.add(jMenu4);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jMenu1.setText("Compras");

        compraRegistrar.setText("registrar Compra");
        compraRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                compraRegistrarActionPerformed(evt);
            }
        });
        jMenu1.add(compraRegistrar);

        jMenuBar1.add(jMenu1);

        crearClientes.setText("Clientes");

        crearCliente.setText("Crear");
        crearCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                crearClienteActionPerformed(evt);
            }
        });
        crearClientes.add(crearCliente);

        modificarClientes.setText("Modificar");
        modificarClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modificarClientesActionPerformed(evt);
            }
        });
        crearClientes.add(modificarClientes);

        borrarClientes.setText("Borrar");
        borrarClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                borrarClientesActionPerformed(evt);
            }
        });
        crearClientes.add(borrarClientes);

        jMenuBar1.add(crearClientes);

        jMenu5.setText("Productos");

        crearProducto.setText("Crear Facturas");
        crearProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                crearProductoActionPerformed(evt);
            }
        });
        jMenu5.add(crearProducto);

        productoVer.setText("Ver Facturas");
        productoVer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                productoVerActionPerformed(evt);
            }
        });
        jMenu5.add(productoVer);

        jMenuBar1.add(jMenu5);

        jMenu6.setText("Reportes");

        reporteCompra.setText("Compra de Productos");
        reporteCompra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reporteCompraActionPerformed(evt);
            }
        });
        jMenu6.add(reporteCompra);

        reporteVenta.setText("Ventas de Productos");
        reporteVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reporteVentaActionPerformed(evt);
            }
        });
        jMenu6.add(reporteVenta);

        reporteInventario.setText("Inventario");
        reporteInventario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reporteInventarioActionPerformed(evt);
            }
        });
        jMenu6.add(reporteInventario);

        jMenuBar1.add(jMenu6);

        jMenu7.setText("Usuarios");

        usuarioCrear.setText("Crear Usuario");
        usuarioCrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usuarioCrearActionPerformed(evt);
            }
        });
        jMenu7.add(usuarioCrear);

        usuarioModificar.setText("Modificar Usuario");
        usuarioModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usuarioModificarActionPerformed(evt);
            }
        });
        jMenu7.add(usuarioModificar);

        usuarioBorrar.setText("Borrar Usuario");
        usuarioBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usuarioBorrarActionPerformed(evt);
            }
        });
        jMenu7.add(usuarioBorrar);

        jMenuBar1.add(jMenu7);

        jMenu8.setText("Acerca de");

        opcInfo.setText("info");
        opcInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opcInfoActionPerformed(evt);
            }
        });
        jMenu8.add(opcInfo);

        jMenuBar1.add(jMenu8);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(escritorio, javax.swing.GroupLayout.PREFERRED_SIZE, 655, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(escritorio, javax.swing.GroupLayout.PREFERRED_SIZE, 366, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void opcInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opcInfoActionPerformed
        // TODO add your handling code here:
        cargarInfo verInfo = new cargarInfo();
        escritorio.add(verInfo);
        verInfo.show();
    }//GEN-LAST:event_opcInfoActionPerformed

    private void crearClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_crearClienteActionPerformed
        // TODO add your handling code here:
        clientesCrear Crearcliente = new clientesCrear();
        escritorio.add(Crearcliente);
        Crearcliente.show();
    }//GEN-LAST:event_crearClienteActionPerformed

    private void modificarClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modificarClientesActionPerformed
        // TODO add your handling code here:
        clientesModificar Modificarclientes = new clientesModificar();
        escritorio.add(Modificarclientes);
        Modificarclientes.show();
    }//GEN-LAST:event_modificarClientesActionPerformed

    private void borrarClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_borrarClientesActionPerformed
        // TODO add your handling code here:
        clientesBorrar Borrarclientes = new clientesBorrar();
        escritorio.add(Borrarclientes);
        Borrarclientes.show();
    }//GEN-LAST:event_borrarClientesActionPerformed

    private void usuarioCrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usuarioCrearActionPerformed
        // TODO add your handling code here:
        infoUsuarios crearUsuario = new infoUsuarios();
        escritorio.add(crearUsuario);
        crearUsuario.show();
    }//GEN-LAST:event_usuarioCrearActionPerformed

    private void usuarioModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usuarioModificarActionPerformed
        // TODO add your handling code here:
        modificarUsuario usuariomodificar =new modificarUsuario();
        escritorio.add(usuariomodificar);
        usuariomodificar.show();
    }//GEN-LAST:event_usuarioModificarActionPerformed

    private void usuarioBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usuarioBorrarActionPerformed
        // TODO add your handling code here:
        borrarUsuario usuarioborrar = new borrarUsuario();
        escritorio.add(usuarioborrar);
        usuarioborrar.show();
    }//GEN-LAST:event_usuarioBorrarActionPerformed

    private void compraRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_compraRegistrarActionPerformed
        // TODO add your handling code here:
        comprasRegistrar comprasregistrar = new comprasRegistrar();
        escritorio.add(comprasregistrar);
        comprasregistrar.show();
    }//GEN-LAST:event_compraRegistrarActionPerformed

    private void crearProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_crearProductoActionPerformed
        // TODO add your handling code here:
        crearFactura crearfactura = new crearFactura();
        escritorio.add(crearfactura);
        crearfactura.show();
    }//GEN-LAST:event_crearProductoActionPerformed

    private void productoVerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_productoVerActionPerformed
        // TODO add your handling code here:
        verFactura verfactura = new verFactura();
        escritorio.add(verfactura);
        verfactura.show();
    }//GEN-LAST:event_productoVerActionPerformed

    private void reporteCompraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reporteCompraActionPerformed
        // TODO add your handling code here:
        reporteCompra reportecompra = new reporteCompra();
        escritorio.add(reportecompra);
        reportecompra.show();
    }//GEN-LAST:event_reporteCompraActionPerformed

    private void reporteVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reporteVentaActionPerformed
        // TODO add your handling code here:
        reporteVenta reporteventa = new reporteVenta();
        escritorio.add(reporteventa);
        reporteventa.show();
    }//GEN-LAST:event_reporteVentaActionPerformed

    private void reporteInventarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reporteInventarioActionPerformed
        // TODO add your handling code here:
        reporteInventario reporteinventario = new reporteInventario();
        escritorio.add(reporteinventario);
        reporteinventario.show();
    }//GEN-LAST:event_reporteInventarioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem borrarClientes;
    private javax.swing.JMenuItem compraRegistrar;
    private javax.swing.JMenuItem crearCliente;
    private javax.swing.JMenu crearClientes;
    private javax.swing.JMenuItem crearProducto;
    private javax.swing.JDesktopPane escritorio;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenu jMenu8;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuItem modificarClientes;
    private javax.swing.JMenuItem opcInfo;
    private javax.swing.JMenuItem productoVer;
    private javax.swing.JMenuItem reporteCompra;
    private javax.swing.JMenuItem reporteInventario;
    private javax.swing.JMenuItem reporteVenta;
    private javax.swing.JMenuItem usuarioBorrar;
    private javax.swing.JMenuItem usuarioCrear;
    private javax.swing.JMenuItem usuarioModificar;
    // End of variables declaration//GEN-END:variables
}
